spring.application.name=WtcSync

# H2 Database (in-memory)
spring.datasource.url=jdbc:h2:mem:wtcsync
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.h2.console.enabled=true
spring.flyway.enabled=false

# JWT
jwt.secret=WtcSyncSecretKeyParaTokenJWTQueDeveTer256BitsMinimo2026
jwt.expiration=86400000
